# -*- coding: utf-8 -*-
"""2revizyon3syn paper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTSsT1FDHEWRugGSo4cx4qQKtEFq3FRO
"""

!pip install ete3 biopython PyQt5 statannotations

"""
Ancestral Sequence Reconstruction — "Alanine-Centric" Model
============================================================
Reconstructs ancestral amino acid states at every internal node of the
phylogenetic tree using Fitch parsimony, then focuses specifically on
positions where the deepest shared ancestor carries Alanine (A) and
traces how those positions diverge to Threonine (T) or Valine (V) in
daughter lineages, with special attention to the Input_seq_ATOM_A clade.

Outputs
-------
1. ancestral_ala_analysis.png  – multi-panel figure
2. ala_divergence_table.csv    – per-position divergence summary
3. per_node_asr.csv            – full ancestral state table (all nodes × sites)
"""

import sys, warnings, textwrap
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
from matplotlib.colors import ListedColormap
from collections import defaultdict, Counter
from Bio import AlignIO
from ete3 import Tree

# ──────────────────────────────────────────────────────────────────────────────
# 1.  Load data
# ──────────────────────────────────────────────────────────────────────────────
ALN_PATH  = "msa_fasta.aln"
TREE_PATH = "TheTree.txt"

print("Loading alignment …")
aln = AlignIO.read(ALN_PATH, "fasta")
n_seq   = len(aln)
aln_len = aln.get_alignment_length()
seq_dict = {r.id: str(r.seq).upper() for r in aln}
print(f"  {n_seq} sequences × {aln_len} alignment columns")

print("Loading tree …")
tree = Tree(open(TREE_PATH).read().strip(), format=1)
leaves = tree.get_leaf_names()
print(f"  {len(leaves)} leaves")

# Index internal nodes
for idx, node in enumerate(tree.traverse("postorder")):
    node.name = node.name if node.is_leaf() else f"NODE_{idx}"

# ──────────────────────────────────────────────────────────────────────────────
# 2.  Fitch Parsimony — ancestral reconstruction
# ──────────────────────────────────────────────────────────────────────────────
GAPS = {'-', 'X', '?', 'B', 'Z'}

def fitch_up(node, col_idx):
    """Bottom-up pass: returns the Fitch set and parsimony score."""
    if node.is_leaf():
        aa = seq_dict.get(node.name, '-')[col_idx]
        node._fitch_set = {aa} if aa not in GAPS else set()
        node._fitch_score = 0
        return node._fitch_set, 0

    child_sets, child_scores = [], []
    for child in node.children:
        cs, sc = fitch_up(child, col_idx)
        child_sets.append(cs)
        child_scores.append(sc)

    total_score = sum(child_scores)
    intersection = child_sets[0].copy()
    for cs in child_sets[1:]:
        intersection &= cs

    if intersection:
        node._fitch_set   = intersection
        node._fitch_score = 0
    else:
        union = set()
        for cs in child_sets:
            union |= cs
        node._fitch_set   = union
        node._fitch_score = 1

    node._fitch_score += total_score
    return node._fitch_set, node._fitch_score


def fitch_down(node, parent_state=None):
    """Top-down pass: select a single state from the Fitch set."""
    fset = node._fitch_set
    if not fset:                       # gap/unknown — inherit or mark '?'
        node._anc_state = parent_state if parent_state else '?'
    elif parent_state and parent_state in fset:
        node._anc_state = parent_state
    else:
        # Prefer A > T > V > alphabetical for the Ala-centric analysis
        for pref in ['A', 'T', 'V']:
            if pref in fset:
                node._anc_state = pref
                break
        else:
            node._anc_state = sorted(fset)[0]

    for child in node.children:
        fitch_down(child, node._anc_state)


print("Running Fitch parsimony across all alignment columns …")
node_states = {}          # node.name → list of states, length = aln_len
for node in tree.traverse():
    node_states[node.name] = ['?'] * aln_len

for col in range(aln_len):
    fitch_up(tree, col)
    fitch_down(tree, None)
    for node in tree.traverse():
        node_states[node.name][col] = node._anc_state

print("  Done.")

# ──────────────────────────────────────────────────────────────────────────────
# 3.  Identify "Alanine-centric" positions
#     = columns where the ROOT ancestral state is Alanine
# ──────────────────────────────────────────────────────────────────────────────
root_states = node_states[tree.name]
ala_cols    = [i for i, aa in enumerate(root_states) if aa == 'A']
print(f"\nAlanine at ROOT: {len(ala_cols)} / {aln_len} columns")

# Input_seq column states
inp_states = list(seq_dict['Input_seq_ATOM_A'])

# ──────────────────────────────────────────────────────────────────────────────
# 4.  For each Ala column: find the earliest divergence to T or V
#     "divergence node" = deepest node (closest to root) that carries T or V
# ──────────────────────────────────────────────────────────────────────────────
TARGET = {'T', 'V'}

def depth_of(node):
    d = 0
    n = node
    while n.up:
        d += 1
        n = n.up
    return d


records = []
for col in ala_cols:
    for target_aa in TARGET:
        # Walk postorder; find the one with smallest depth that shows target_aa
        earliest = None
        earliest_depth = 9999
        for node in tree.traverse("preorder"):
            if node_states[node.name][col] == target_aa:
                d = depth_of(node)
                if d < earliest_depth:
                    earliest_depth = d
                    earliest        = node
        if earliest is None:
            continue

        # Determine if Input_seq is in the T or V subtree
        inp_aa        = inp_states[col]
        inp_in_target = (inp_aa == target_aa)

        records.append({
            "col_1based"    : col + 1,
            "root_aa"       : 'A',
            "diverge_aa"    : target_aa,
            "diverge_node"  : earliest.name,
            "diverge_depth" : earliest_depth,
            "inp_aa"        : inp_aa if inp_aa not in GAPS else 'gap',
            "inp_matches_div": inp_in_target,
        })

div_df = pd.DataFrame(records)
print(f"\nAla-divergence events found: {len(div_df)}")
print(div_df.groupby("diverge_aa")["col_1based"].count().to_string())

# ──────────────────────────────────────────────────────────────────────────────
# 5.  Subtree amino-acid composition after each divergence node
# ──────────────────────────────────────────────────────────────────────────────
def subtree_leaf_aas(node, col):
    aas = []
    for leaf in node.get_leaves():
        aa = seq_dict.get(leaf.name, '-')[col]
        if aa not in GAPS:
            aas.append(aa)
    return aas


# Aggregate for T-divergence vs V-divergence
t_cols = div_df[div_df.diverge_aa == 'T']['col_1based'].values - 1
v_cols = div_df[div_df.diverge_aa == 'V']['col_1based'].values - 1

def aa_dist(cols, node_filter_aa):
    """Leaf aa distribution for columns where diverge_aa == node_filter_aa."""
    counter = Counter()
    for col in cols:
        # find the node where divergence first happens
        rows = div_df[(div_df.col_1based == col+1) &
                      (div_df.diverge_aa == node_filter_aa)]
        if rows.empty:
            continue
        for _, row in rows.iterrows():
            node_name = row["diverge_node"]
            results   = tree.search_nodes(name=node_name)
            node_obj  = results[0] if results else None
            if node_obj is None:
                continue
            counter.update(subtree_leaf_aas(node_obj, col))
    return counter

t_dist = aa_dist(t_cols, 'T')
v_dist = aa_dist(v_cols, 'V')

# ──────────────────────────────────────────────────────────────────────────────
# 6.  Input_seq positional analysis at Ala-columns
# ──────────────────────────────────────────────────────────────────────────────
inp_summary = div_df.groupby(["diverge_aa", "inp_aa"]).size().reset_index(name='count')
print("\nInput_seq state at A→T/V divergence columns:")
print(inp_summary.to_string(index=False))

# Positions where Input_seq ITSELF shows A (same as root)
inp_retains_ala = [c for c in ala_cols if inp_states[c] == 'A']
inp_to_t        = [c for c in ala_cols if inp_states[c] == 'T']
inp_to_v        = [c for c in ala_cols if inp_states[c] == 'V']

print(f"\nInput_seq retains A at root-A columns : {len(inp_retains_ala)}")
print(f"Input_seq has T at root-A columns     : {len(inp_to_t)}")
print(f"Input_seq has V at root-A columns     : {len(inp_to_v)}")

# ──────────────────────────────────────────────────────────────────────────────
# 7.  Build a heatmap of ancestral states along Ala-columns (internal nodes)
# ──────────────────────────────────────────────────────────────────────────────
# Use up to 60 most informative Ala-columns (highest leaf variability)
def col_variability(col):
    aas = [seq_dict[l][col] for l in leaves if seq_dict[l][col] not in GAPS]
    return len(set(aas))

if len(ala_cols) > 60:
    ala_cols_plot = sorted(ala_cols,
                           key=lambda c: col_variability(c), reverse=True)[:60]
else:
    ala_cols_plot = ala_cols

# Internal nodes sorted by depth (root first)
int_nodes_sorted = sorted(
    [n for n in tree.traverse() if not n.is_leaf()],
    key=lambda n: depth_of(n)
)
int_node_names = [n.name for n in int_nodes_sorted][:40]  # top 40 shallowest

AA_STATES = ['A', 'T', 'V', 'S', 'G', 'I', 'L', 'other', '?']
AA_COLORS = {
    'A': '#2196F3',   # blue  — Alanine (focal)
    'T': '#F44336',   # red   — Threonine
    'V': '#4CAF50',   # green — Valine
    'S': '#FF9800',   # orange — Serine
    'G': '#9C27B0',   # purple — Glycine
    'I': '#00BCD4',   # cyan  — Isoleucine
    'L': '#8BC34A',   # light-green — Leucine
    'other': '#BDBDBD',
    '?': '#FFFFFF',
}

def encode_aa(aa):
    if aa in AA_COLORS:
        return aa
    elif aa in GAPS or aa == '?':
        return '?'
    else:
        return 'other'


heatmap_data = []
for node_name in int_node_names:
    row = [encode_aa(node_states[node_name][c]) for c in ala_cols_plot]
    heatmap_data.append(row)

# Convert to numeric for imshow
aa_to_int = {aa: i for i, aa in enumerate(AA_STATES)}
heat_numeric = np.array(
    [[aa_to_int[cell] for cell in row] for row in heatmap_data],
    dtype=float
)

# ──────────────────────────────────────────────────────────────────────────────
# 8.  Depth distribution of first A→T vs A→V divergence events
# ──────────────────────────────────────────────────────────────────────────────
depth_T = div_df[div_df.diverge_aa == 'T']['diverge_depth'].values
depth_V = div_df[div_df.diverge_aa == 'V']['diverge_depth'].values

# ──────────────────────────────────────────────────────────────────────────────
# 9.  Per-column: track the full A → T/V path for Input_seq neighbourhood
#     (closest relatives in tree that share A, T, or V at that column)
# ──────────────────────────────────────────────────────────────────────────────
# Find the clade containing Input_seq
input_node = tree.search_nodes(name='Input_seq_ATOM_A')[0]
input_ancestors = []
n = input_node
while n.up:
    n = n.up
    input_ancestors.append(n.name)

# Ancestral states along Input_seq lineage for Ala-columns
lineage_states = []
lineage_labels = []
for anc_name in input_ancestors[:20]:  # top 20 ancestors (root-wards)
    states_at_ala = [node_states[anc_name][c] for c in ala_cols_plot]
    lineage_states.append(states_at_ala)
    lineage_labels.append(anc_name.replace("NODE_", "N"))

lineage_numeric = np.array(
    [[aa_to_int[encode_aa(aa)] for aa in row] for row in lineage_states],
    dtype=float
)

# ──────────────────────────────────────────────────────────────────────────────
# 10.  FIGURE
# ──────────────────────────────────────────────────────────────────────────────
print("\nGenerating figure …")
fig = plt.figure(figsize=(22, 20))
fig.patch.set_facecolor('#0F1117')

gs = gridspec.GridSpec(
    3, 3,
    figure=fig,
    hspace=0.45, wspace=0.40,
    top=0.90, bottom=0.06, left=0.07, right=0.97
)

cmap_custom = ListedColormap([AA_COLORS[aa] for aa in AA_STATES])

def style_ax(ax, title, xlabel='', ylabel=''):
    ax.set_facecolor('#1A1D27')
    ax.tick_params(colors='#CCCCCC', labelsize=7)
    ax.xaxis.label.set_color('#CCCCCC')
    ax.yaxis.label.set_color('#CCCCCC')
    ax.title.set_color('#FFFFFF')
    ax.set_title(title, fontsize=10, fontweight='bold', pad=6)
    ax.set_xlabel(xlabel, fontsize=8)
    ax.set_ylabel(ylabel, fontsize=8)
    for spine in ax.spines.values():
        spine.set_edgecolor('#444444')

# ── Legend (shared) ──────────────────────────────────────────────────────────
legend_patches = [
    mpatches.Patch(color=AA_COLORS['A'],     label='Alanine (A)  — ancestral focus'),
    mpatches.Patch(color=AA_COLORS['T'],     label='Threonine (T)  — divergence target'),
    mpatches.Patch(color=AA_COLORS['V'],     label='Valine (V)  — divergence target'),
    mpatches.Patch(color=AA_COLORS['S'],     label='Serine (S)'),
    mpatches.Patch(color=AA_COLORS['G'],     label='Glycine (G)'),
    mpatches.Patch(color=AA_COLORS['I'],     label='Isoleucine (I)'),
    mpatches.Patch(color=AA_COLORS['L'],     label='Leucine (L)'),
    mpatches.Patch(color=AA_COLORS['other'], label='Other AA'),
    mpatches.Patch(color=AA_COLORS['?'],     label='Gap / Unknown'),
]
fig.legend(
    handles=legend_patches,
    loc='upper right', ncol=3, fontsize=8,
    facecolor='#1A1D27', edgecolor='#444444',
    labelcolor='#CCCCCC',
    bbox_to_anchor=(0.97, 0.97)
)

# ── Panel A: Heatmap — all internal nodes × Ala-columns ─────────────────────
ax_heat = fig.add_subplot(gs[0, :2])
im = ax_heat.imshow(
    heat_numeric, aspect='auto', cmap=cmap_custom,
    vmin=0, vmax=len(AA_STATES)-1, interpolation='nearest'
)
ax_heat.set_yticks(range(len(int_node_names)))
ax_heat.set_yticklabels([n.replace("NODE_", "N") for n in int_node_names],
                         fontsize=5)
ax_heat.set_xticks(range(0, len(ala_cols_plot), max(1, len(ala_cols_plot)//10)))
ax_heat.set_xticklabels(
    [str(ala_cols_plot[i]+1) for i in range(0, len(ala_cols_plot),
                                              max(1, len(ala_cols_plot)//10))],
    fontsize=6
)
style_ax(ax_heat,
         f"Ancestral AA States — Internal Nodes × Root-Alanine Columns\n"
         f"(Root→shallowest; {len(ala_cols_plot)} of {len(ala_cols)} Ala-columns shown)",
         xlabel="Alignment column (1-based)", ylabel="Internal node (root → leaves)")
# Draw horizontal line at root
ax_heat.axhline(-0.5, color='white', lw=1.5, ls='--')

# ── Panel B: Input_seq lineage heatmap ───────────────────────────────────────
ax_lin = fig.add_subplot(gs[0, 2])
im2 = ax_lin.imshow(
    lineage_numeric, aspect='auto', cmap=cmap_custom,
    vmin=0, vmax=len(AA_STATES)-1, interpolation='nearest'
)
ax_lin.set_yticks(range(len(lineage_labels)))
ax_lin.set_yticklabels(lineage_labels, fontsize=5)
ax_lin.set_xticks(range(0, lineage_numeric.shape[1],
                         max(1, lineage_numeric.shape[1]//8)))
ax_lin.set_xticklabels(
    [str(ala_cols_plot[i]+1)
     for i in range(0, lineage_numeric.shape[1],
                    max(1, lineage_numeric.shape[1]//8))],
    fontsize=6
)
style_ax(ax_lin,
         "Input_seq Lineage\n(Ancestral path, root→tip)",
         xlabel="Ala-column", ylabel="Ancestor")

# ── Panel C: Depth distribution of A→T vs A→V divergence ────────────────────
ax_dep = fig.add_subplot(gs[1, 0])
bins = range(0, int(max(max(depth_T, default=0), max(depth_V, default=0)))+2)
ax_dep.hist(depth_T, bins=bins, alpha=0.75, color=AA_COLORS['T'],
            label=f'A→T (n={len(depth_T)})', edgecolor='white', lw=0.3)
ax_dep.hist(depth_V, bins=bins, alpha=0.75, color=AA_COLORS['V'],
            label=f'A→V (n={len(depth_V)})', edgecolor='white', lw=0.3)
ax_dep.axvline(np.median(depth_T) if len(depth_T) else 0,
               color=AA_COLORS['T'], ls='--', lw=1.5,
               label=f'Median T depth={np.median(depth_T):.0f}' if len(depth_T) else '')
ax_dep.axvline(np.median(depth_V) if len(depth_V) else 0,
               color=AA_COLORS['V'], ls='--', lw=1.5,
               label=f'Median V depth={np.median(depth_V):.0f}' if len(depth_V) else '')
ax_dep.legend(fontsize=6, facecolor='#1A1D27', labelcolor='#CCCCCC',
               edgecolor='#444444')
style_ax(ax_dep, "Depth of First A→T / A→V\nDivergence Node",
         xlabel="Tree depth (edges from root)", ylabel="Number of columns")

# ── Panel D: AA composition inside T-divergent subtrees ──────────────────────
ax_tdist = fig.add_subplot(gs[1, 1])
top_t = t_dist.most_common(10)
if top_t:
    labels_t, vals_t = zip(*top_t)
    colors_t = [AA_COLORS.get(aa, AA_COLORS['other']) for aa in labels_t]
    bars = ax_tdist.bar(range(len(labels_t)), vals_t, color=colors_t,
                         edgecolor='white', lw=0.5)
    ax_tdist.set_xticks(range(len(labels_t)))
    ax_tdist.set_xticklabels(labels_t, fontsize=9, color='#EEEEEE')
    for bar, val in zip(bars, vals_t):
        ax_tdist.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
                       str(val), ha='center', va='bottom', fontsize=7,
                       color='white')
style_ax(ax_tdist, "Leaf AA Distribution\nin A→T Subtrees",
         xlabel="Amino acid", ylabel="Leaf count")

# ── Panel E: AA composition inside V-divergent subtrees ──────────────────────
ax_vdist = fig.add_subplot(gs[1, 2])
top_v = v_dist.most_common(10)
if top_v:
    labels_v, vals_v = zip(*top_v)
    colors_v = [AA_COLORS.get(aa, AA_COLORS['other']) for aa in labels_v]
    bars = ax_vdist.bar(range(len(labels_v)), vals_v, color=colors_v,
                         edgecolor='white', lw=0.5)
    ax_vdist.set_xticks(range(len(labels_v)))
    ax_vdist.set_xticklabels(labels_v, fontsize=9, color='#EEEEEE')
    for bar, val in zip(bars, vals_v):
        ax_vdist.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
                       str(val), ha='center', va='bottom', fontsize=7,
                       color='white')
style_ax(ax_vdist, "Leaf AA Distribution\nin A→V Subtrees",
         xlabel="Amino acid", ylabel="Leaf count")

# ── Panel F: Input_seq state breakdown at Ala-columns ────────────────────────
ax_inp = fig.add_subplot(gs[2, 0])
inp_counts = Counter()
for c in ala_cols:
    aa = inp_states[c]
    if aa in GAPS:
        inp_counts['gap'] += 1
    else:
        inp_counts[aa] += 1

sorted_inp = sorted(inp_counts.items(), key=lambda x: -x[1])
labels_i = [x[0] for x in sorted_inp]
vals_i   = [x[1] for x in sorted_inp]
colors_i = [AA_COLORS.get(aa, '#888888') for aa in labels_i]
bars = ax_inp.bar(range(len(labels_i)), vals_i, color=colors_i,
                   edgecolor='white', lw=0.5)
ax_inp.set_xticks(range(len(labels_i)))
ax_inp.set_xticklabels(labels_i, fontsize=8, color='#EEEEEE')
for bar, val in zip(bars, vals_i):
    ax_inp.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                 str(val), ha='center', va='bottom', fontsize=7, color='white')
style_ax(ax_inp,
         "Input_seq States at\nRoot-Alanine Columns",
         xlabel="Amino acid (in Input_seq)", ylabel="Column count")

# ── Panel G: Stacked A/T/V proportion across alignment (sliding window) ──────
ax_prop = fig.add_subplot(gs[2, 1:])
WIN = 20
proportions = {'A': [], 'T': [], 'V': [], 'other': []}
cols_x = []
for start in range(0, aln_len - WIN + 1, WIN // 2):
    end = start + WIN
    window_cols = range(start, end)
    a_cnt = t_cnt = v_cnt = o_cnt = 0
    for col in window_cols:
        for leaf in leaves:
            aa = seq_dict[leaf][col]
            if aa == 'A': a_cnt += 1
            elif aa == 'T': t_cnt += 1
            elif aa == 'V': v_cnt += 1
            elif aa not in GAPS: o_cnt += 1
    total = a_cnt + t_cnt + v_cnt + o_cnt
    if total == 0: total = 1
    proportions['A'].append(a_cnt / total)
    proportions['T'].append(t_cnt / total)
    proportions['V'].append(v_cnt / total)
    proportions['other'].append(o_cnt / total)
    cols_x.append((start + end) / 2)

cols_x = np.array(cols_x)
bot = np.zeros(len(cols_x))
for aa, color in [('A', AA_COLORS['A']), ('T', AA_COLORS['T']),
                   ('V', AA_COLORS['V']), ('other', AA_COLORS['other'])]:
    vals = np.array(proportions[aa])
    ax_prop.fill_between(cols_x, bot, bot + vals, color=color,
                          alpha=0.85, label=aa)
    bot += vals

# Mark Ala-columns with small ticks
for ac in ala_cols:
    ax_prop.axvline(ac, color='white', alpha=0.08, lw=0.5)
ax_prop.set_xlim(0, aln_len)
ax_prop.set_ylim(0, 1)
ax_prop.legend(fontsize=7, facecolor='#1A1D27', labelcolor='#CCCCCC',
                edgecolor='#444444', loc='upper right')
style_ax(ax_prop,
         f"A / T / V Composition Across Alignment (window={WIN} cols)\n"
         "White ticks = root-Alanine columns",
         xlabel="Alignment column", ylabel="Proportion of leaves")

# ── Title ─────────────────────────────────────────────────────────────────────
fig.text(0.50, 0.965,
         'Ancestral Sequence Reconstruction — Alanine-Centric Divergence Model',
         ha='center', va='top', fontsize=15, fontweight='bold', color='white')
fig.text(0.50, 0.945,
         f'150 sequences · 349-column MSA · Fitch Parsimony · '
         f'Root-Ala sites: {len(ala_cols)} · A→T events: {len(depth_T)} · A→V events: {len(depth_V)}',
         ha='center', va='top', fontsize=8.5, color='#AAAAAA')

out_fig = 'ancestral_ala_analysis.png'
plt.savefig(out_fig, dpi=160, bbox_inches='tight', facecolor=fig.get_facecolor())
print(f"  Figure saved → {out_fig}")

# ──────────────────────────────────────────────────────────────────────────────
# 11.  Save tables
# ──────────────────────────────────────────────────────────────────────────────
div_df.to_csv('ala_divergence_table.csv', index=False)
print("  Divergence table saved → ala_divergence_table.csv")

# Full per-node ancestral state table (internal nodes × Ala-columns)
node_df = pd.DataFrame(
    {n: [node_states[n][c] for c in ala_cols] for n in int_node_names},
    index=[c+1 for c in ala_cols]   # 1-based column numbers
).T
node_df.index.name = 'node'
node_df.to_csv('per_node_asr.csv')
print("  Per-node ASR table saved → per_node_asr.csv")

# ──────────────────────────────────────────────────────────────────────────────
# 12.  Console summary
# ──────────────────────────────────────────────────────────────────────────────
print()
print("=" * 70)
print("  ALANINE-CENTRIC ANCESTRAL RECONSTRUCTION SUMMARY")
print("=" * 70)
print(f"  Alignment: {n_seq} seqs × {aln_len} cols")
print(f"  Root-Alanine columns: {len(ala_cols)}")
print()
print("  Divergence from Ala at root:")
for daa in ['T', 'V']:
    sub = div_df[div_df.diverge_aa == daa]
    med = sub['diverge_depth'].median() if len(sub) else 0
    print(f"    A→{daa}: {len(sub):3d} events  |  median divergence depth: {med:.1f}")
print()
print("  Input_seq_ATOM_A at root-Ala columns:")
for aa, cnt in sorted(inp_counts.items(), key=lambda x: -x[1]):
    print(f"    {aa:>5s}: {cnt}")
print()
print("  Input_seq retains A (same as root):    ", len(inp_retains_ala), "columns")
print("  Input_seq diverged → T:                ", len(inp_to_t), "columns")
print("  Input_seq diverged → V:                ", len(inp_to_v), "columns")
print("=" * 70)

# ──────────────────────────────────────────────────────────────────────────────
# FIGURE SETTINGS + STATS IMPORTS
# ──────────────────────────────────────────────────────────────────────────────
import scipy.stats as stats
from scipy.spatial.distance import jensenshannon

# ──────────────────────────────────────────────────────────────────────────────
# UPDATED COLORS (publication-friendly)
# ──────────────────────────────────────────────────────────────────────────────
AA_COLORS = {
    'A': '#1f77b4',
    'T': '#d62728',
    'V': '#2ca02c',
    'S': '#ff7f0e',
    'G': '#9467bd',
    'I': '#17becf',
    'L': '#8c564b',
    'other': '#7f7f7f',
    '?': '#ffffff',
}

# ──────────────────────────────────────────────────────────────────────────────
# CLEAN STYLE FUNCTION WITH PANEL LABELS
# ──────────────────────────────────────────────────────────────────────────────
def style_ax(ax, title, xlabel='', ylabel='', panel_label=None):
    ax.set_facecolor('white')

    ax.tick_params(colors='black', labelsize=8)
    ax.xaxis.label.set_color('black')
    ax.yaxis.label.set_color('black')

    ax.set_title(title, fontsize=11, fontweight='bold', pad=8)
    ax.set_xlabel(xlabel, fontsize=9)
    ax.set_ylabel(ylabel, fontsize=9)

    for spine in ax.spines.values():
        spine.set_edgecolor('#333333')
        spine.set_linewidth(0.8)

    if panel_label:
        ax.text(-0.08, 1.05, panel_label,
                transform=ax.transAxes,
                fontsize=13, fontweight='bold')

# ──────────────────────────────────────────────────────────────────────────────
# FIGURE
# ──────────────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(22, 20))
fig.patch.set_facecolor('white')

gs = gridspec.GridSpec(
    3, 3,
    figure=fig,
    hspace=0.45, wspace=0.35,
    top=0.92, bottom=0.06, left=0.07, right=0.97
)

cmap_custom = ListedColormap([AA_COLORS[aa] for aa in AA_STATES])

# ── Panel A: Heatmap ─────────────────────────────────────────────────────────
ax_heat = fig.add_subplot(gs[0, :2])
im = ax_heat.imshow(heat_numeric, aspect='auto',
                    cmap=cmap_custom,
                    vmin=0, vmax=len(AA_STATES)-1)

ax_heat.set_yticks(range(len(int_node_names)))
ax_heat.set_yticklabels([n.replace("NODE_", "N") for n in int_node_names], fontsize=6)

ax_heat.set_xticks(range(0, len(ala_cols_plot), max(1, len(ala_cols_plot)//10)))
ax_heat.set_xticklabels([str(ala_cols_plot[i]+1)
                         for i in range(0, len(ala_cols_plot),
                                        max(1, len(ala_cols_plot)//10))],
                        fontsize=7)

# gridlines
ax_heat.set_xticks(np.arange(-.5, len(ala_cols_plot), 1), minor=True)
ax_heat.set_yticks(np.arange(-.5, len(int_node_names), 1), minor=True)
ax_heat.grid(which='minor', color='lightgray', linestyle='-', linewidth=0.2)
ax_heat.tick_params(which='minor', bottom=False, left=False)

style_ax(ax_heat,
         "Ancestral AA States (Internal Nodes × Root-Ala Columns)",
         "Alignment column", "Internal node",
         panel_label='a)')

# ── Panel B: Lineage ─────────────────────────────────────────────────────────
ax_lin = fig.add_subplot(gs[0, 2])
ax_lin.imshow(lineage_numeric, aspect='auto',
              cmap=cmap_custom,
              vmin=0, vmax=len(AA_STATES)-1)

style_ax(ax_lin,
         "Input_seq lineage (root→tip)",
         "Ala-columns", "Ancestor",
         panel_label='b)')

# ── Panel C: Depth distribution + STATS ──────────────────────────────────────
ax_dep = fig.add_subplot(gs[1, 0])

ax_dep.hist(depth_T, alpha=0.6, label='A→T', edgecolor='black')
ax_dep.hist(depth_V, alpha=0.6, label='A→V', edgecolor='black')

# Mann-Whitney U test
if len(depth_T) > 0 and len(depth_V) > 0:
    u_stat, p_val = stats.mannwhitneyu(depth_T, depth_V, alternative='two-sided')
    ax_dep.text(0.95, 0.95,
                f'U={u_stat:.1f}\np={p_val:.2e}',
                transform=ax_dep.transAxes,
                ha='right', va='top', fontsize=9)

ax_dep.legend()
ax_dep.grid(axis='y', linestyle='--', alpha=0.4)

style_ax(ax_dep,
         "Depth of divergence (A→T vs A→V)",
         "Tree depth", "Count",
         panel_label='c)')

# ── Panel D/E: Composition + JS divergence ───────────────────────────────────
def plot_dist(ax, dist, title, panel_label):
    items = dist.most_common(10)
    if not items:
        return

    labels, vals = zip(*items)
    colors = [AA_COLORS.get(a, '#999') for a in labels]

    ax.bar(labels, vals, color=colors, edgecolor='black')
    ax.grid(axis='y', linestyle='--', alpha=0.3)

    style_ax(ax, title, "AA", "Count", panel_label)

ax_tdist = fig.add_subplot(gs[1, 1])
plot_dist(ax_tdist, t_dist, "A→T subtree composition", 'd)')

ax_vdist = fig.add_subplot(gs[1, 2])
plot_dist(ax_vdist, v_dist, "A→V subtree composition", 'e)')

# JS divergence
def normalize(counter):
    total = sum(counter.values())
    return np.array([counter.get(k, 0)/total for k in AA_STATES if k not in ['?']])

if t_dist and v_dist:
    p = normalize(t_dist)
    q = normalize(v_dist)
    jsd = jensenshannon(p, q)

    ax_vdist.text(0.95, 0.95,
                  f'JS divergence={jsd:.3f}',
                  transform=ax_vdist.transAxes,
                  ha='right', va='top', fontsize=9)

# ── Panel F: Input_seq stats + Chi-square ────────────────────────────────────
ax_inp = fig.add_subplot(gs[2, 0])

inp_counts = Counter(inp_states[c] if inp_states[c] not in GAPS else 'gap'
                     for c in ala_cols)

labels, vals = zip(*sorted(inp_counts.items(), key=lambda x: -x[1]))
colors = [AA_COLORS.get(a, '#999') for a in labels]

ax_inp.bar(labels, vals, color=colors, edgecolor='black')

# Chi-square vs uniform
chi2, p = stats.chisquare(vals)

ax_inp.text(0.95, 0.95,
            f'χ²={chi2:.1f}\np={p:.2e}',
            transform=ax_inp.transAxes,
            ha='right', va='top', fontsize=9)

ax_inp.grid(axis='y', linestyle='--', alpha=0.3)

style_ax(ax_inp,
         "Input_seq states at root-Ala sites",
         "AA", "Count",
         panel_label='f)')

# ── Panel G: Composition landscape ───────────────────────────────────────────
ax_prop = fig.add_subplot(gs[2, 1:])

bot = np.zeros(len(cols_x))
for aa in ['A', 'T', 'V', 'other']:
    vals = np.array(proportions[aa])
    ax_prop.fill_between(cols_x, bot, bot + vals,
                         alpha=0.7, label=aa)
    bot += vals

ax_prop.grid(True, linestyle='--', alpha=0.3)
ax_prop.legend()

style_ax(ax_prop,
         "A/T/V composition across alignment",
         "Alignment column", "Proportion",
         panel_label='g)')

# ── Title ────────────────────────────────────────────────────────────────────
fig.text(0.5, 0.97,
         'Alanine-Centric Ancestral Sequence Divergence',
         ha='center', fontsize=16, fontweight='bold')

fig.text(0.5, 0.945,
         f'{n_seq} sequences · {aln_len} positions · '
         f'Root-Ala: {len(ala_cols)} · A→T: {len(depth_T)} · A→V: {len(depth_V)}',
         ha='center', fontsize=10)

# ── Save ─────────────────────────────────────────────────────────────────────
plt.savefig('ancestral_ala_analysis.png', dpi=300, bbox_inches='tight')