# -*- coding: utf-8 -*-
"""revizyon3syn paper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAYg5qrp3ds8uOF7hEWundg36XErFAPz
"""

!pip install pandas numpy seaborn matplotlib scipy

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu
import re
import os

# ==========================================
# 1. Load Data from all 8 files
# ==========================================
file_list = [
    'SV2A.xlsx - Sheet1.csv', 'SV2B.xlsx - Sheet1.csv', 'SV2C.xlsx - Sheet1.csv',
    'SYNGR1.xlsx - Sheet1.csv', 'SYNGR2.xlsx - Sheet1.csv', 'SYNGR3.xlsx - Sheet1.csv',
    'SYNGR4.xlsx - Sheet1.csv', 'SYP.xlsx - Sheet1.csv'
]

dfs = []
for file in file_list:
    if os.path.exists(file):
        # Read using latin1 to avoid special character crashes
        df_temp = pd.read_csv(file, encoding='latin1')
        dfs.append(df_temp)
    else:
        print(f"Warning: File not found: {file}")

# Combine all datasets into one DataFrame
df = pd.concat(dfs, ignore_index=True)
print(f"Total variants loaded: {len(df)}")

# ==========================================
# 2. Fix Frequencies and Filter for Rare Variants
# ==========================================
# The exported Allele Frequency column has scientific notation errors.
# We calculate the true frequency mathematically:
df['Calculated_AF'] = df['Allele Count'] / df['Allele Number']

# Keep rare missense variants (MAF < 0.01)
if 'VEP Annotation' in df.columns:
    df_rare = df[(df['VEP Annotation'] == 'missense_variant') & (df['Calculated_AF'] < 0.01)].copy()
else:
    df_rare = df[df['Calculated_AF'] < 0.01].copy()

# ==========================================
# 3. Classify Variants
# ==========================================
aa_map = {
    'Ala': 'A', 'Arg': 'R', 'Asn': 'N', 'Asp': 'D', 'Cys': 'C',
    'Gln': 'Q', 'Glu': 'E', 'Gly': 'G', 'His': 'H', 'Ile': 'I',
    'Leu': 'L', 'Lys': 'K', 'Met': 'M', 'Phe': 'F', 'Pro': 'P',
    'Ser': 'S', 'Thr': 'T', 'Trp': 'W', 'Tyr': 'Y', 'Val': 'V'
}

qty_pairs = [('L', 'Q'), ('V', 'T'), ('I', 'T'), ('F', 'Y')]
rqty_pairs = [('Q', 'L'), ('T', 'V'), ('T', 'I'), ('Y', 'F')]

def classify_variant(protein_consequence):
    if pd.isna(protein_consequence):
        return 'Unknown'

    # Extract the amino acid changes
    match = re.search(r'p\.([A-Z][a-z]{2})\d+([A-Z][a-z]{2})', str(protein_consequence))
    if match:
        aa1 = aa_map.get(match.group(1))
        aa2 = aa_map.get(match.group(2))

        pair = (aa1, aa2)
        if pair in qty_pairs:
            return 'QTY Variant'
        elif pair in rqty_pairs:
            return 'rQTY Variant'
        else:
            return 'Other Missense'
    return 'Unknown'

df_rare['Variant Class'] = df_rare['Protein Consequence'].apply(classify_variant)
df_analysis = df_rare[df_rare['Variant Class'] != 'Unknown']

print("\nVariant classification counts:")
print(df_analysis['Variant Class'].value_counts())

# ==========================================
# 4. Statistical Testing
# ==========================================
qty_rqty_freqs = df_analysis[df_analysis['Variant Class'].isin(['QTY Variant', 'rQTY Variant'])]['Calculated_AF']
other_freqs = df_analysis[df_analysis['Variant Class'] == 'Other Missense']['Calculated_AF']

p_val_display = "N/A"
if len(qty_rqty_freqs) > 0 and len(other_freqs) > 0:
    # Test if QTY/rQTY variants have higher frequencies than Other Missense variants
    stat, p_val = mannwhitneyu(qty_rqty_freqs, other_freqs, alternative='greater')
    p_val_display = f"{p_val:.4f}"
    print(f"\nMann-Whitney U test (QTY/rQTY > Other Missense): p-value = {p_val:.4e}")
else:
    print("\nNote: No 'Other Missense' variants found in the files. Skipping the comparative statistical test.")

# ==========================================
# 5. Generate Visualizations
# ==========================================
sns.set_theme(style="whitegrid", context="talk")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

colors = {'QTY Variant': '#2ecc71', 'rQTY Variant': '#3498db', 'Other Missense': '#e74c3c'}

# Filter categories that actually exist in the data to avoid plotting empty categories
existing_classes = df_analysis['Variant Class'].unique().tolist()
order = [c for c in ['QTY Variant', 'rQTY Variant', 'Other Missense'] if c in existing_classes]

# --- Plot A: Boxplot ---
sns.boxplot(
    data=df_analysis, x='Variant Class', y='Calculated_AF',
    palette=colors, ax=axes[0], order=order, showfliers=False
)
sns.stripplot(
    data=df_analysis, x='Variant Class', y='Calculated_AF',
    color='black', alpha=0.5, jitter=True, ax=axes[0], order=order
)
axes[0].set_yscale('log')
axes[0].set_title('Comparative MAF Boxplot (Log Scale)')
axes[0].set_ylabel('Minor Allele Frequency (MAF)')
axes[0].set_xlabel('')

# --- Plot B: SFS Density Plot ---
sns.histplot(
    data=df_analysis, x='Calculated_AF', hue='Variant Class',
    element='step', stat='density', common_norm=False,
    palette=colors, log_scale=True, ax=axes[1], hue_order=order, alpha=0.3, linewidth=2
)
axes[1].set_title('Site Frequency Spectrum (SFS)')
axes[1].set_xlabel('Minor Allele Frequency (MAF, Log Scale)')
axes[1].set_ylabel('Density')

title_str = 'Population Frequencies of Variants Across All 8 Proteins (gnomAD MAF < 0.01)'
if p_val_display != "N/A":
    title_str += f'\nMann-Whitney U p-value (QTY/rQTY vs Others): {p_val_display}'
fig.suptitle(title_str, fontsize=16)

plt.tight_layout()
output_filename = 'Combined_Variant_Analysis.png'
plt.savefig(output_filename, dpi=300, bbox_inches='tight')
print(f"\nAnalysis complete. Plot saved successfully as '{output_filename}'")
plt.show()